### ISSUE TITLE
Background Images not showing in preview

### ISSUE THREAD

**Issue by XanderCam** [jasonday/printThis#103]
Error received in console:
Uncaught ReferenceError: $ is not defined
Which should reflect that jQuery is needed.
But it does not stop everything else from working.

Real Problem: 
Images are not loading, tho text and CSS are.

Also I had to add "folder" variable to script as your original script didn't look in the correct folder:
added to line 117: baseURL = baseURL + '/' + opt.folder + '/'
use as option: 
$('.product-info').printThis({
  			  importCSS: true,
			  canvas: true,
			  folder: 'new2',
			  loadCSS: 'css/colors.css'
});

Images are loaded into a gallery div as background images:
**<div class="content" style="background-image: url(../Bilder/els.png);"></div>**

Other images on page is loaded as I should expect.
After some experimenting it is clear that images loaded as Background Image - does NOT display in the printing div. Images loaded the normal way works as expected.

See image for illustration:
![untitled-1](https://cloud.githubusercontent.com/assets/6030883/24472105/c52d15fe-14c4-11e7-97d9-c875ac133fe7.jpg)

====================================================================

###### `[  http://www.innotec.nu/new2/ `  

Your issue may be closed without active code to debug. Options include jsfiddle, jsbin, codepen, dropbox, etc. with code highlighting the specific issue you are having

====================================================================

#### Steps to reproduce the problem

1. Upon opening page outside scandinavia, please click Norwegian Flag upon request 
2. click a Grey button with text: "Les Mer"  
3. Click "PRODUKTINFORMASJON"
4. Click Printer Icon in top left corner  

====================================================================

#### What is the expected behaviour?

Inside of the DIV should show all content in print preview

====================================================================

#### What is the observed behaviour?

Every picture except the ones in gallery are shown

====================================================================

#### When you set `debug:true` and inspect the iframe, what do you see?
Uncaught ReferenceError: $ is not defined
    at <anonymous>:2:5
    at p (jquery-3.0.0.min.js:2)
    at Ha (jquery-3.0.0.min.js:3)
    at r.fn.init.append (jquery-3.0.0.min.js:3)
    at printThis.js:163
(anonymous) @ VM17071:2
p @ jquery-3.0.0.min.js:2
Ha @ jquery-3.0.0.min.js:3
append @ jquery-3.0.0.min.js:3
(anonymous) @ printThis.js:163
VM17073:3 Uncaught ReferenceError: retrieveJSON is not defined
    at <anonymous>:3:1
    at p (jquery-3.0.0.min.js:2)
    at Ha (jquery-3.0.0.min.js:3)
    at r.fn.init.append (jquery-3.0.0.min.js:3)
    at printThis.js:163

====================================================================

#### More Details

- Which browsers/versions does it happen on?
ALL Browsers
- Which printThis version are you using?
1.9.1
- Did this work before?
First time I use this script

**Comment by jasonday** [comment]
Thanks for the detailed information.

Can you please include `debug: true`, so that I can look at the page. I am not sure what is causing the jQuery issue, but the images issue is due to browser print behavior. Browsers, by default, do not print background images. This is an option when the user prints and there is no way to force the print of background images. 

A couple of solutions:

1. Use a different image gallery that does not use background images.
2. Create print only markup that is the primary image as an <img> tag
3. You may be able to force background images with `webkit-print-color-adjust: exact;` with Chrome & Safari, but I don't believe support is widespread

**Comment by oculus42** [comment]
Background images do not print by default in browsers. It looks like most of your images are set to be  backgrounds.

There are a number of scripts inside the content area you are printing, which appears to be causing the jQuery error. printThis doesn't load all the scripts from your page, because it is duplicating "rendered" content. Ideally your scripts are not intermingled with your content in this way.

You can work around this by cloning the print section and discarding the scripts before calling `.printThis()`:

```javascript
$('.product-info').clone().find('script').remove().end().printThis();
```

That clears out the script errors. If you can't rearrange your page so the printable content doesn't have scripts in it, this is a decent workaround. 

Next up, for some reason there is an issue with the base URL, which is adding `undefined` to the URLs of resources. **This seems to be a bug we need to research.**   

You have added an invalid option: `folder: 'new2'`. You were probably aiming for the `base` option. I made it much farther with the following command:

```javascript
$('.product-info').clone().find('script').remove().end().printThis({
    base: '//' + document.location.host + '/new2/',
    importCSS: true,
    loadCSS: 'css/colors.css'
});
```

The main images are still missing. I'll spend a few minutes to see if that's all just background-image issues, or if there's something else at work.

**Comment by oculus42** [comment]
I agree with @jasonday that your best solution is finding an image gallery that doesn't use background images. I slapped this together, which is by no means the best solution, but gets something on the screen... it extracts the background image url and makes an image tag with it. 

```javascript
$('.product-info').clone()
    .find('script').remove().end()
    .find('.image.active .content').each(function() { 
        this.innerHTML = '<img src="' + this.style.backgroundImage.replace('url("','').replace('")','') + '" style="max-width: 100%; max-height: 100%;">';
        this.style.backgroundImage = '';
    }).end()
    .printThis({
        base: '//' + document.location.host + '/new2/',
        importCSS: true,
        loadCSS: 'css/colors.css',
        printDelay: 500
    });
```

**Comment by XanderCam** [comment]
Thank you for your response.
The "$('.product-info').clone().find('script').remove().end().printThis({" did remove the Jquery errors.

I agree that I should get a different gallery - but for now I've created a workaround.
I add the main photo as an image with class hidden. Then upon printing, I hide the gallery and remove the display:none from the hidden image. Thus replacing the gallery with a single photo - which for now is sufficient.

is there a way to set part of the div content as "non-printable", without tending to Jquery workarounds ?

**Comment by jasonday** [comment]
Using a print stylesheet is the preferred method to hide or show specific
elements.

**Comment by oculus42** [comment]
Agreed. You can go a couple of different directions. This covers *most* cases, and allows you to set `print-only` on inline or block items. This may also be useful for accessibility, because you can put an alt tag on the image which would be handled by braille devices, as well.

```css
@media screen {
  .print-only { display: none; }
}
```

**Comment by XanderCam** [comment]
That helped.
@media print  {
  .print-only { display: none; }
}

to the rescue :)
Thank you.
