### ISSUE TITLE
getting focus back on main window after print

### ISSUE THREAD

**Issue by mimhof1** [jasonday/printThis#106]
Greetings, what I thought was lost focus turns out to be caused be trying to clone jquery and  canvasjs into the iframe so I can print some charts, once iframe is removed, I'm losing jquery functions.  I'll dive in and see if a better way to bring in some js into the iframe without causing issues once removed.  Any thoughts would be great.

**Comment by oculus42** [comment]
Are you adding jQuery and canvas in using the `header` or `footer` options?
These options were originally intended to take strings, so when you use a jQuery selector, the *original* is pulled from the page. 

This was fixed in 1.9.1, which I just discovered was not published to npm. 1.9.1 is now available through npm.

You can work around this in prior versions using the jQuery `.clone()` method:

```javascript
$('.myContent').printThis({
  header: $('.myHeader').clone();
});
```

Also, you should not need to include any scripts to clone an existing canvas. `printThis` references the original `<canvas>` to copy content to the print iframe.

Please let us know if any of this solved your problem. If not, additional information such as an example of your code and which version of printThis would be helpful.

**Comment by oculus42** [comment]
@mimhof1 Any follow up? It's been three weeks?

**Comment by mimhof1** [comment]
Hi Samuel....not yet, we had to put that down for now.  Once we circle back
and if see if that works then will advuse, thanks!

**Comment by jasonday** [comment]
Closing issue; no further response.
