### ISSUE TITLE
printThis can't check print finished

### ISSUE THREAD

**Issue by tinhphaistc** [jasonday/printThis#110]
i use printThis jQuery plugin and i want to use code check to close print window but this code not working. plugin printThis: https://github.com/jasonday/printThis and code check to close: http://stackoverflow.com/a/18325463/1579865
help me please Thanks

**Comment by oculus42** [comment]
There are a *lot* of varying responses and methods in the StackOverflow post you provided, with various levels of success on different browsers. 

Many of the solutions are event-driven, so you could add the event listeners before you call `.printThis()` and see if those work without any changes to the plugin.

Because printThis is loaded in an iframe, I do not know if it would be able to listen to some of proposed solutions.

**Comment by jasonday** [comment]
Closing issue; no further response.
