### ISSUE TITLE
Separate print of <div's is OK,,  but together the output is incorrect.

### ISSUE THREAD

**Issue by obrienj970** [jasonday/printThis#144]
> short description of the bug / issue, provide more detail below.
I want to print 2 <div blocks in the same print output.  The content of the blocks is generated by Google Maps Directions service, one is the map and the other is a list of directions.

If I print them separately using printThis(), they each print fine.  The map is complete and the list of directions is a full multi-page list;

If I try to print them in the same call $('#mapdiv, #dirdiv").printThis(),  I get the map at the top left of the page (correct) and a partial list at the lower right (incorrect). All on a single page..

One caveat, when printed separately, the options are slightly different as I must use "canvas: true" for the map or I don't get the blue route line thus in the single call case, "canvas: true" is specified.

Why is this happening,  is there a way to correct it, or is there a way to combine the separately "printed" outputs into one print output.

====================================================================

###### `[  paste a link to an example (demo or active link) of the issue here ]`  

Your issue may be closed without active code to debug. Options include jsfiddle, jsbin, codepen, dropbox, etc. with code highlighting the specific issue you are having

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is the observed behaviour?

...  

====================================================================

#### When you set `debug:true` and inspect the iframe, what do you see?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which printThis version are you using?
- Did this work before?

**Comment by jasonday** [comment]
A. Have you set `debug:true` and inspected the printThis `<iframe>`?
B. Have you checked the CSS? It sounds like you are having a layout issue which is likely due to CSS (you're pulling pieces of the page into a new page and you may need additional CSS to manage the bits)

**Comment by obrienj970** [comment]
I have tried debug: true in the failing case and the iframe is empty except for the header I specified.

If its a CSS problem, how come it works if I printThis for each <div separately.

**Comment by obrienj970** [comment]
I made,a mistake when I said debug showed a blank iframe.  That was on another test of this issue.

I will go back and look at the iframe in the referenced test of try to print both in one call.

Sorry.

**Comment by jasonday** [comment]
Additional info: The reason this is likely a layout/CSS issue is because you are getting both portions intended, but the formatting is not correct. CSS is relationship driven, so when you pull different portions of a page into a new document, that relationship is changed and may need additional CSS to adjust.

**Comment by obrienj970** [comment]
When I get home I'll post the definition for the <div blocks but I have no control overvwhat Google Maps may do.

Is there away to change CSS between the 2 divs while printThis is processing?

I have no problem modifying the code to do what I want?

**Comment by obrienj970** [comment]
Jason,

Could you give me some guidance as to where in the code I can detect that a switch in selector is occurring.  I have and idea as to how to solve my problem but I'm having trouble finding where the switch occurs.

Regards,
Jim

**Comment by jasonday** [comment]
Hi @obrienj970, I think you're thinking about this all wrong, or we're having an communication issue. 

Either way, let's verify the two statements below:

1. printThis is working. Utilizing multiple selectors both elements are successfully included in the print.
2. The layout of those elements is not what you desire

If both of those are true, then I can explain the issue and the fix:

printThis works by creating a new document in an iframe and cloning the selected elements (the selectors you want printed) from the parent page to the new iframe. This iframe is what is being printed (not the original document). 

Because only portions of the original document are being included in the new iframe, the relationship of the elements changes and the CSS from the parent document may not be able to address this change. 

I believe this is what is happening on your printed document. You are selecting two elements and when they are copied into the iframe, the CSS doesn't account for this new relationship. 

The good news is that this is an easy fix - you need to add additional CSS (either through `loadCSS` or through a `@media print` query in your CSS) that will adjust the layout to the layout you want in the print document.  Even with the google map output, you can add CSS to make adjustments in the printed layout.

**Comment by obrienj970** [comment]
Jason,

You are correct in your assumptions and I have come to the conclusion that I may need to do in my own code something similar to what printThis does but specifically for the Google Maps Direction Service "output" so it prints as I need it to.

As printThis works beautifully elsewhere in my site, I will continue to use it there.

I'm also thinking about two callbacks in a modified version of your code, one before print for iframe mods and the second when print is finished to clean up mods if necessary but I'm still thinking about that approach.

Regardless, thank you for your help.  Great piece of work.

**Comment by jasonday** [comment]
Again, I will call out that you can affect the Google Maps Direction Service "output" print with CSS and there's no need for the modified version of printThis.

**Comment by jasonday** [comment]
Here's a suggestion:

- set the `debug: true` option
- open up the web developer tools
- inspect the iframe that printThis creates
- increase the iframe size so that you can see the content (add CSS in web dev tools)
- play with the CSS to get to the layout you want
- put the CSS into an `@media print` query in your CSS

and you're done.
