### ISSUE TITLE
Box on first page if printContainer=true

### ISSUE THREAD

**Issue by galcott** [jasonday/printThis#171]
I just found this plugin and it's great but I'm having one small issue. If printContainer is set to true then I am getting a box printed on the top half of the first page of the printout as shown in this screenshot. The box seems to be the same size regardless of the content of the printout. I can avoid this by setting printContainer=false but it definitely seems like a bug that you should look into.
![printout](https://user-images.githubusercontent.com/4509764/50525709-32d4c100-0aab-11e9-9569-55824f3dd55d.jpg)

**Comment by jasonday** [comment]
That box is likely due to some CSS or layout that is being applied (a float element, etc.). PrintThis does not impose any CSS styles, as it pulls CSS from the parent page.

You can determine the cause by setting `debug:true` and inspecting the print iframe contents. Then set some rules in your CSS to apply when printing using `@media print {}`
