### ISSUE TITLE
Horizontal scroll table data not printing in chrome browser.

### ISSUE THREAD

**Issue by VenkateshBaddepuri** [jasonday/printThis#179]
Please go through below fiddle link.
https://jsfiddle.net/yacm1h2n/

I am not able to print whole page in chrome browser. It is cutoff the page after 20th record. But the same is working fine in Firefox browser.
please find screenshot for reference.
![firefox](https://user-images.githubusercontent.com/14120861/59613667-ece4e580-913c-11e9-896b-7a9ac635f7f9.png)
![chrome](https://user-images.githubusercontent.com/14120861/59613678-f2dac680-913c-11e9-85d8-21a4e2ed6dcf.png)

Thanks in advance !

**Comment by jasonday** [comment]
So it appears that this isn't a bug in printThis, but in how chrome handles scaling. IE and others are automatically applying scaling to fit the table on the page, but chrome does not by default. Users would need to set this setting individually - https://superuser.com/questions/979741/how-can-i-make-chrome-shrink-to-fit-on-printing

Based on that, you'll have to either reduce the font size or scale the table using @media print if you want the table to fit to page without asking your users to set that option. Basic example: https://jsfiddle.net/knexj5q1/

Additionally, in your demo, you have to use the `importStyle: true` option due to how jsfiddle includes the CSS.
