### ISSUE TITLE
Print without the printer selection dialog

### ISSUE THREAD

**Issue by pithhelmet8669** [jasonday/printThis#184]
**Describe the bug**
Option to display or not display the print selection dialog

**To Reproduce**
1 - Create normal div to print
2 - Fire the print event
3 - ** DISPLAYS the printer selection dialog
4 - Normal operations

**Expected behavior**
If the option to print to default is enabled, do not display the printer selection dialog

**Comment by jasonday** [comment]
To clarify, you are requesting that an option be added to not display the browser's print dialog?
For security reasons your browser requires that the print dialog prompt  before printing, otherwise any website could print without permission. printThis cannot override this behavior. 

There are some use cases where printing without the dialog is desired (such as a kiosk), but printThis would have no control over that behavior, and the kiosk setup would need to account for it through print settings, etc.

**Comment by pithhelmet8669** [comment]
okey dokey - thank you
