### ISSUE TITLE
the afterPrint method is called before the print window

### ISSUE THREAD

**Issue by taprom** [jasonday/printThis#216]
**Describe the bug**
the afterPrint method is called before the print window

![image](https://user-images.githubusercontent.com/48086753/100183446-8c50ff00-2f11-11eb-9b52-bcd38aa09c04.png)

**Comment by jasonday** [comment]
Yeah, unfortunately that is a possible bug. I originally did not want to add that option because it's not based on a real event, but based on timing of the browser print dialog. The browser print dialog halts javascript when open, however depending on timing or on platform (desktop vs mobile), the javascript may execute before the browser halts all javascript. 

You may be able to counteract the bug by adding a `setTimeout()` to the `alert()`
