### ISSUE TITLE
Huge SVG size (fontawesome) when printing

### ISSUE THREAD

**Issue by mTeden** [jasonday/printThis#220]
**Describe the bug**
When creating an SVG-image with fontawesome <i class="fa fas-times"></i> it appears very very large when printing with printThis.
I tried to change css with beforePrint-method to x-small, but nothing changed.

**Desktop (please complete the following information):**
Edge, Firefox, Chrome (latest)

Best regards
#
** Screenshot **
https://ibb.co/bFjVTnz

**Comment by jasonday** [comment]
A couple of thoughts:
* When a portion of the page is moved to the print iframe, the CSS cascade bit can become broken because a parent selector is no longer available. For example if I have a class on the body such as `body.myClass` and I want to print a container, but that container refers to the body class such as `body.myClass .myContainer`, when that container is moved to the print iframe the cascade from `body.myClass` is no longer viable, so won't apply to the container. This could be occurring in your print selection with the icon
* Try print specific CSS. In your CSS add print media query and address the size of the icons directly.
