### ISSUE TITLE
Custom TTF fonts not printing

### ISSUE THREAD

**Issue by galcott** [jasonday/printThis#230]
I'm using custom TTF fonts on a page that show up correctly on screen but when I use printThis to print the section they are printing as Times Roman. I don't know if this is specifically a printThis issue or some other issue involving printing custom fonts. Is there a way to correct this? The fonts are declared like this.

```
     @font-face {
       font-family: Clearface;
       src: url('ClearfaceNormal.ttf');
       font-weight: normal;
     }
     @font-face {
       font-family: Clearface;
       src: url('ClearfaceBold.ttf');
       font-weight: bold;
     }

```

**Comment by jasonday** [comment]
printThis works by creating an iframe and copying elements into it. The issue here is that the CSS is referencing a relative path not available in the iframe. printThis requires a full qualified URL for references. In this case, you could use the `loadCSS` parameter to pull in the necessary font files.

**Comment by galcott** [comment]
Well, I have to say that getting a response 7 months after my post is very timely! I actually figured this out a long time ago though I don't remember how.
