### ISSUE TITLE
Google maps not showing route line

### ISSUE THREAD

**Issue by leeDav** [jasonday/printThis#32]
When using a Bootstrap modal to display a map with a form (so the user can generate directions) the route line doesn't show (in Chrome, Safari, and Firefox -- all Mac OSX 10.9).

It displays in Chrome's Print Preview (printing from the browser menu) but not when using printThis.

My first assumption was it was a scope thing as I was creating a new map object when the modal was launched (thereby showing no route line when the modal is re-opened), but even after changing this the route line still appears in the modal but not when printing.

Any thoughts would be most welcome.

Here's the JS I'm using to trigger printThis:

``` javascript
$('#print_directions').on('click', function(ev) {
        ev.preventDefault();

        $('#printSection').printThis( {
                debug: false,
                importCSS:true,
                printContainer: false,
                pageTitle: "Getting here",
                printDelay: 333,
                header: null,
            });
    });
});
```

For example, here's Print Preview in Chrome as if I were printing normally;
![image](https://cloud.githubusercontent.com/assets/2325076/3409875/a67ff6f8-fdde-11e3-8bf5-4c7b1e2d67af.png)

And here's the Print Preview when using printThis.
![image](https://cloud.githubusercontent.com/assets/2325076/3409885/c2971088-fdde-11e3-9543-937b09924008.png)

**Comment by madsparky** [comment]
Hi Jason
I am having the same issue. Is there a workaround for this issue?

Cheers

**Comment by jasonday** [comment]
Unfortunately, I do not. I worked with @leeDav external to this thread, and could not find a viable solution. The issue is that when the plugin copies the html elements over to the iframe for printing, the scripting is not re-executed against those element and the canvas route line is not rendered.

One option is to generate a back up static map, https://developers.google.com/maps/documentation/staticmaps/.

When a user clicks print, you cold have this element be the printed element rather than the live map. This would solve the bulk of the issues. 

If I can get some time over the next few days, I'll see if I can put together a demo.

**Comment by madsparky** [comment]
Ok. Thanks. I will give it a crack
