### ISSUE TITLE
about:blank at top right

### ISSUE THREAD

**Issue by tones31** [jasonday/printThis#42]
When printing a page using this plugin I always get "about:blank" at the top right of the page.

**Comment by jasonday** [comment]
This happens because of the way printThis works. The plugin creates a new
html page in an iframe and the element you are wanting to print is copied
over to that iframe. When the iframe is created, it does not associated
with an actual html file, so it's created with the about blank.

`<iframe src='about:blank'>`

Some browsers put the url on pages you print from the web and
unfortunately, I'm unable to control that from within the plugin.
