### ISSUE TITLE
In Internet Explorer, sometimes the entire page prints

### ISSUE THREAD

**Issue by caseyjhol** [jasonday/printThis#43]
This is probably related to #26. I initially thought this was an issue strictly with IE9, but I came across it in IE11 as well. On one page of my site, printThis works great in IE11 (still buggy in IE9), but there's another page where printThis doesn't work, and prints the entire page instead in all versions of IE. There aren't any discernible differences. Printing works fine in Firefox and Chrome on all of these pages.

My solution was to replace this:

```javascript
$iframe[0].contentWindow.focus();
$iframe[0].contentWindow.print();
```

with

```javascript
if (document.queryCommandSupported('print')) {
    $iframe[0].contentWindow.document.execCommand('print', false, null);
} else {
    $iframe[0].contentWindow.focus();
    $iframe[0].contentWindow.print();
}
```
This relies on `execCommand('print', false, null)` in browsers that support it, and falls back to `print()` for browsers that don't (Firefox). I haven't performed extensive testing on this yet, but it seems to work for my purposes for now. Any issues with using `execCommand('print', false, null)`?

**Comment by jasonday** [comment]
Thanks for this; I'll take a look. I'm not familiar with  execCommand('print', false, null),  so I will need some time to review. IE can be flakey, and will take longer to create and write to an iframe; that's why the printDelay option was necessary - to avoid a race condition, which may have been what you were running into. 
On 2/24/2015 8:03:54 PM, caseyjhol <notifications@github.com> wrote:
This is probably related to #26 [https://github.com/jasonday/printThis/issues/26]. I initially thought this was an issue strictly with IE9, but I came across it in IE11 as well. On one page of my site, printThis works great in IE11 (still buggy in IE9), but there's another page where printThis doesn't work, and prints the entire page instead in all versions of IE. There aren't any discernible differences. Printing works fine in Firefox and Chrome on all of these pages.
My solution was to replace this:
$iframe[0].contentWindow.focus(); $iframe[0].contentWindow.print();
with
if (document.queryCommandSupported('print')) { $iframe[0].contentWindow.document.execCommand('print', false, null); } else { $iframe[0].contentWindow.focus(); $iframe[0].contentWindow.print(); }
This relies on execCommand('print', false, null) in browsers that support it, and falls back to print() for browsers that don't (Firefox). I haven't performed extensive testing on this yet, but it seems to work for my purposes for now. Any issues with using execCommand('print', false, null)?
&mdash;
