### ISSUE TITLE
Print page is blank in Chrome

### ISSUE THREAD

**Issue by cosecantt** [jasonday/printThis#53]
Hi Jason,
I am using printThis ( with printDelay: 500 option) in my projects however there is one issue I am frequently facing.
My printing page data is pulled from the server by ajax which is invoice. Sometimes it shows blank page in Chrome if some data is not pulled fully. If I try second time it works fine since the images are cached in the browser. 
Since the latest Chrome 46.0.2490.80m update it prints always blank with option printDelay: 500, even 2000. 
Anything am I missing? Thank you.
Note: There is no any browser or js error.

**Comment by jasonday** [comment]
Hi,

When are you executing  printThis?
On ajax:success?

You might try $.done -
$.ajax({url: '/'}).done(function(data) { $('#container).printThis (); });

Let me know if that works, or send me an example page/jsfiddle example.

Thanks,

Jason

Hi Jason,
I am using printThis ( with printDelay: 500 option) in my projects however
there is one issue I am frequently facing.
My printing page data is pulled from the server by ajax which is invoice.
Sometimes it shows blank page in Chrome if some data is not pulled fully.
If I try second time it works fine since the images are cached in the
browser.
Since the latest Chrome 46.0.2490.80m update it prints always blank with
option printDelay: 500, even 2000.
Anything am I missing? Thank you.

—
Reply to this email directly or view it on GitHub
<https://github.com/jasonday/printThis/issues/53>.
