### ISSUE TITLE
Close dialog on "Cancel" button click

### ISSUE THREAD

**Issue by hemalait** [jasonday/printThis#75]
I am using printThis to print a certain portion of my page by opening this content in a new dialog and opening the print selection dialog after a delay of 500. I want to know if I can add functionality to the Cancel button of the print dialog to close the whole dialog. I don't want user to stay on that dialog  as it just has the content to print and no other way to print that section. 

$("#btnPrint").on('click',function(e){     
      $("#leadsheet_report").printThis({
      title: "Lead Sheet Report",
      printDelay: 500
      });
      });

**Comment by jasonday** [comment]
Unfortunately, because the print dialog is controlled by the browser, you cannot listen for or do anything with that event. Fortunately, the browser halts javascript execution while the print dialog is open. You could execute a dialog.close after the printThis code, which should give you the expected behavior.
